version: '3'
services:
  web:
    build: .
    # volumes:
    #   - .:/code  # can be useful for development, but not working on ubuntu (https://stackoverflow.com/q/44694086)
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: starships
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
