apiVersion: apps/v1
kind: Deployment
metadata:
  name: starships-app-deployment
  labels: 
    app: starships-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starships-app
  template:  # this applies to a pod
    metadata:
      labels:
        app: starships-app
    spec:  # spec (blueprint) for a pod
      containers:
        - name: starships-app
          image: starships-app:1.0
          env:
            - name: POSTGRES_NAME
              value: starships
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_PORT
              value: "5432"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service  # it makes sense to have the service and the deployment in the same file
metadata:
  name: starships-app-service
spec:
  selector:
    app: starships-app  # points to the deployment label and template label 'app: nginx'
  type: LoadBalancer    # (optional) makes it an external services
  ports:
    - protocol: TCP
      port: 8000       # listens on port 80
      targetPort: 8000 # forward request to pods port 8080 (this should match the 'containerPort')
      nodePort: 30001  # (optional) port exposed by the external service (must be between 30000 and 32767)
